repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ruff-isort
        name: ruff-isort
        entry: ruff check --select I --fix --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: biome-format
        name: biome-format
        entry: biome format --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types_or: [text]
        files: "\\.js$"
        require_serial: true
