version: "3"

services:
  redis:
    image: docker.io/library/redis:7.2.4-alpine

    ports:
      - 127.0.0.1:6379:6379

    volumes:
      - ./data/redis:/data

    configs:
      - source: redis.conf
        target: /usr/local/etc/redis/redis.conf

  pg:
    image: docker.io/postgis/postgis:16-3.4-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openstreetmap
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=C

    ports:
      - 127.0.0.1:5432:5432

    volumes:
      - ./data/pg:/var/lib/postgresql/data

  pgAdmin:
    image: docker.io/dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@osm.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DISABLE_POSTFIX: 1
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"

    ports:
      - 127.0.0.1:5433:80

    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

    configs:
      - source: servers.json
        target: /pgadmin4/servers.json

configs:
  redis.conf:
    content: |
      # authentication
      requirepass redis

      # no persistence
      save ""
      appendonly no

      # automatically delete keys
      maxmemory 128mb
      maxmemory-policy allkeys-lru

  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "openstreetmap",
            "Group": "Servers",
            "Host": "pg",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "PasswordExecCommand": "echo postgres"
          }
        }
      }
