version: "3"

services:
  db:
    image: postgis/postgis:16-3.4-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openstreetmap
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=C

    ports:
      - 127.0.0.1:5432:5432

    volumes:
      - ./data/db:/var/lib/postgresql/data
