name: Python tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-23.11-darwin

      - name: Extract nixpkgs hash
        run: |
          nixpkgs_hash=$(egrep -o 'archive/[0-9a-f]{40}\.tar\.gz' shell.nix | cut -d'/' -f2 | cut -d'.' -f1)
          echo "NIXPKGS_HASH=$nixpkgs_hash" >> $GITHUB_ENV

      - name: Cache Nix store
        uses: actions/cache@v4
        id: nix-cache
        with:
          key: nix-${{ runner.os }}-${{ env.NIXPKGS_HASH }}
          path: /tmp/nix-cache

      - name: Import Nix store cache
        if: steps.nix-cache.outputs.cache-hit == 'true'
        run: |
          nix-store --import < /tmp/nix-cache

      - name: Cache Python venv
        uses: actions/cache@v4
        with:
          key: python-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          path: |
            ~/.cache/pypoetry
            .venv

      - name: Cache Bun packages
        uses: actions/cache@v4
        with:
          key: bun-${{ runner.os }}-${{ hashFiles('bun.lockb') }}
          path: ~/.bun/install/cache

      - name: Cache locale
        uses: actions/cache@v4
        with:
          key: locale-${{ runner.os }}
          path: |
            config/locale/gnu
            config/locale/i18next
            config/locale/postprocess

      - name: Install dependencies
        run: |
          nix-shell --pure --run true

      - name: Export Nix store cache
        if: steps.nix-cache.outputs.cache-hit != 'true'
        run: |
          nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nix-cache

      - name: Start services
        run: |
          nix-shell --pure --run "dev-start"

      - name: Run tests
        env:
          POSTGRES_LOG: 1
        run: |
          nix-shell --pure --run "run-tests term"
